apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-deployment
spec:
  replicas: 1 # Start with 1, HPA will take over
  selector:
    matchLabels:
      app: iris-app
  template:
    metadata:
      labels:
        app: iris-app
    spec:
      containers:
      - name: iris-app-container
        image: IMAGE_PLACEHOLDER # This is replaced by the GitHub Action
        ports:
        - containerPort: 8080
        # This block is CRITICAL for autoscaling
        resources:
          requests:
            cpu: "250m"  # Request 0.25 of a vCPU
          limits:
            cpu: "500m"  # Set a max limit of 0.5 vCPU
---
apiVersion: v1
kind: Service
metadata:
  name: iris-service
spec:
  type: LoadBalancer # Exposes the app to the internet
  selector:
    app: iris-app
  ports:
  - protocol: TCP
    port: 80       # The public internet port
    targetPort: 8080 # Your app's container port
