apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-deployment
spec:
  replicas: 2 # Run 2 copies of our app
  selector:
    matchLabels:
      app: iris-app
  template:
    metadata:
      labels:
        app: iris-app
    spec:
      containers:
      - name: iris-app-container
        # IMPORTANT: The image path will be replaced by the GitHub workflow
        image: IMAGE_PLACEHOLDER 
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: iris-service
spec:
  type: LoadBalancer # Expose the service to the internet
  selector:
    app: iris-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
