name: Build, Deploy, and Test

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: iris-cluster
  GKE_REGION: asia-south1
  GAR_LOCATION: asia-south1
  REPOSITORY: iris-repo
  IMAGE: iris-app

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Get GKE Credentials
      uses: 'google-github-actions/get-gke-credentials@v1'
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_REGION }}

    - name: Configure Docker
      run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

    - name: Build Docker image
      # Tell Docker where to find your files
      run: docker build -t ${{ env.IMAGE }} ./week_7

    - name: Tag and Push Docker image
      run: |
        docker tag ${{ env.IMAGE }} ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}
        docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}

    - name: Deploy to GKE
      run: |
        # Tell sed and kubectl where your files are
        sed -i 's|IMAGE_PLACEHOLDER|${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}|g' week_7/deployment.yaml
        kubectl apply -f week_7/deployment.yaml
    
    - name: Apply HPA (Autoscaler)
      run: kubectl apply -f week_7/hpa.yaml

    - name: Wait for LoadBalancer IP
      run: |
        echo "Waiting for service IP..."
        sleep 30
        IP=""
        while [ -z $IP ]; do
          sleep 10
          IP=$(kubectl get service iris-service -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          echo "Current IP: $IP"
        done
        echo "IP=$IP" >> $GITHUB_ENV

    - name: Run Stress Test with wrk
      run: |
        sudo apt-get update && sudo apt-get install -y wrk
        echo "Stressing http://${{ env.IP }}/predict"
        wrk -t4 -c100 -d30s -s week_7/script.lua http://${{ env.IP }}/predict
